#!/usr/bin/env bash
# using scp to transfer a file from client to server

if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

file_path="$1"
IP="$2"
user="$3"
key_file="$4"

# make the file copy to the server via scp
scp -i "$key_file" -o StrictHostKeyChecking=no "$file_path" "$user@$IP:~/"
