#!/usr/bin/env bash
# this script installs nginx and updates its config file
# installing nginx
if ! command -v nginx &> /dev/null; then
    sudo apt-get -y install nginx
fi
# Hello World file   

# Create a new index.html file with "Hello World!" content
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Ensure Nginx is configured to listen on port 80 (default configuration)
# Backup the original configuration

# Restart Nginx without using systemctl (use service command instead)
sudo service nginx restart
