#!/usr/bin/env bash
# Configures a new ubuntu machine by installing
# Nginx where it should be listening on port 80
# Serve a page that would return a Hello World string
#

if ! command -v nginx &> /dev/null; then
    sudo apt-get update -y -qq && \
            sudo apt-get install nginx -y
fi
# starting nginx service
sudo service nginx start

# allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index# Creating new index
echo -e "Hello World!" > /var/www/html/index.html

# Setting up /redirect_me to a youtube video
sudo sed -i '/server_name _;/a \\n    location /redirect_me {\n        return 301 https://example.com/new-page;\n    }\n' /etc/nginx/sites-enabled/default

# Restarting nginx
sudo service nginx reload
