#!/usr/bin/env bash
# Script to configure Nginx for redirection
# Install Nginx if not already installed
if ! command -v nginx &> /dev/null; then
    sudo apt-get -y install nginx
fi
sudo sed -i '/server_name _;/a \\n    location /redirect_me {\n        return 301 https://example.com/new-page;\n    }\n' /etc/nginx/sites-available/default

# Reload Nginx to apply changes
sudo service nginx reload
