#!/usr/bin/env bash
# this script installs nginx and updates its config file
# installing nginx
if ! command -v nginx &> /dev/null; then
    sudo apt-get -y install nginx
fi
# Hello World file   

# Create a new index.html file with "Hello World!" content
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Ensure Nginx is configured to listen on port 80 (default configuration)
# Backup the original configuration

sudo sed -i '/server_name _;/a \\n    location /redirect_me {\n        return 301 https://example.com/new-page;\n    }\n' /etc/nginx/sites-available/default
sudo service nginx restart
