#!/usr/bin/env bash
# this script installs nginx and updates its config file
# installing nginx
if ! command -v nginx &> /dev/null; then
    sudo apt-get -y install nginx
fi
# Hello World file   

# Create a new index.html file with "Hello World!" content
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# creating custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.txt > /dev/null
# Ensure Nginx is configured to listen on port 80 (default configuration)
# Backup the original configuration

sudo sed -i '/^\s*location \/ {$/a \\n        error_page 404 /custom_404.txt;\n        location = /custom_404.txt {\n            internal;\n        }\n' /etc/nginx/sites-enabled/default
sudo service nginx restart
