#!/usr/bin/env bash
# this script displays the sentence 'To infinity and beyond' indefinitely
# with a sleep of 2s between each iteration

while true; do
    echo "To infinity and beyond";
    sleep 2;
done
