#!/usr/bin/env bash
# this script kills the process of script for task 4
# shellcheck disable=SC2009
pid=$(ps -ef | grep "4-to_infinity_and_beyond" | grep -v grep | awk '{print $2}')
if [ -n "$pid" ]; then
    kill "$pid"
fi
