#!/usr/bin/env bash
# this script displays "badluck" at the 4th iteration, "goodluck" at the 8th iteration
# - and "Best School" at every other iteration
i=0
while [ $i -lt 10 ]
do
    if [ $i -eq 3 ]
    then
        echo "bad luck"
    elif [ $i -eq 7 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi

    ((i++))
done
