#!/usr/bin/env bash
# this script displays time from 0 to 12hrs, 59 mins
hour=0
while [ $hour -le 12 ]
do
    echo "Hour: $hour"
    minutes=1
    while [ $minutes -le 59 ]
    do
        echo $minutes
        ((minutes++))
    done
    ((hour++))
done
