#!/usr/bin/env bash
# this script list the content of the pwd excluding letters before the - of each filenames
for file in *;
    do
        if [[ -f "$file" ]];
        then
            echo "${file#*-}"
        fi
done
