#!/usr/bin/env bash
# this script resolves some hostnames into a manually configured ip address

#we check if the command needed to be rua as a superuser
if [[ "$EUID" -ne 0 ]]
then
    echo "run this script as root"
    exit 1
fi
echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8   facebook.com" >> /etc/hosts
