#!/usr/bin/env bash
# this script changes nginx user from root to nginx

if ! command -v nginx; then
    sudo apt-get update -qq
    sudo apt-get -y install nginx
fi

# changing the user to nginx
sed  's/user .*$/user nginx;/' etc/nginx/nginx.conf
# making nginx listen on all ports
sed 's/listen 80 .*$/listen 8080 default_server;/' etc/nginx/sites-available/default
sed 's/listen \[::\]:80 .*$/listen \[::\]:8080 default_server;/' etc/nginx/sites-available/default
